GET http://localhost:3000/tablas

###

GET http://localhost:3000/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGlidW5lc0BnbWFpbC5jb20iLCJpYXQiOjE2OTk5NjEwMTgsImV4cCI6MTY5OTk2NDYxOH0.XeYN_IBzA4tecSRVIFjpfEAb8ToNveM_0UmptBhxXK4  

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "matibunes@gmail.com",
    "password": "1005"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "luquitavo@gmail.com",
    "name": "luca",
    "surname": "chami",
    "password": "5050",
    "confirmPassword": "5050"
}

###

GET http://localhost:3000/token
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGlidW5lc0BnbWFpbC5jb20iLCJpYXQiOjE2OTk5NjQ3ODMsImV4cCI6MTcwNzc0MDc4M30.NxRJPSrcgr2_A68DfqGFDn7-mJJhfkDp3MQygD-Zris

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGlidW5lc0BnbWFpbC5jb20iLCJpYXQiOjE2OTkyOTk3MjEsImV4cCI6MTY5OTMwMzMyMX0.tAFaBZ-lMHalrmryo2xoNT8EMcn76IyHgM5-QvB-9Wo"
}

###

DELETE http://localhost:3000/deleteAccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGlidW5lc0BnbWFpbC5jb20iLCJpYXQiOjE2OTk5NjEwMTgsImV4cCI6MTY5OTk2NDYxOH0.XeYN_IBzA4tecSRVIFjpfEAb8ToNveM_0UmptBhxXK4
Content-Type: application/json

{
    "password": "1005"
}